# Generated by Django 4.2.9 on 2024-09-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Date and time when the user was last updated",
                verbose_name="Updated on",
            ),
        ),
    ]
