# Generated by Django 4.2 on 2024-07-03 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="User's name", max_length=255)),
                (
                    "email",
                    models.EmailField(help_text="User's email address", max_length=255),
                ),
                (
                    "username",
                    models.CharField(help_text="User's username", max_length=150),
                ),
                (
                    "password",
                    models.CharField(help_text="User's password", max_length=128),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        help_text="User's profile banner image",
                        max_length=255,
                        upload_to="userprofile/banner/",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        help_text="User's profile picture",
                        max_length=255,
                        upload_to="userprofile/profile_picture/",
                    ),
                ),
            ],
        ),
    ]
