# Generated by Django 4.2 on 2024-07-06 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the course", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the course"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the course was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="Date and time when the course was last updated"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ForumPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the forum post", max_length=200
                    ),
                ),
                ("content", models.TextField(help_text="Content of the forum post")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the post was created",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who created the forum post",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passed",
                    models.BooleanField(
                        help_text="Indicates if the user passed the exam"
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course related to the exam",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="core.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user taking the exam",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enrolled_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the user enrolled in the course",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course the user is enrolled in",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="core.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user enrolled in the course",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issued_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the certification was issued",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="The course for which the certification is provided",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="core.course",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who received the certification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
