# Generated by Django 4.2.9 on 2024-10-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userprofile_description_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="courseId",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Unique ID for the course",
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the lesson",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="picture",
            field=models.ImageField(
                help_text="Lesson picture entered by admin",
                max_length=255,
                null=True,
                upload_to="course/lesson/lessonpicture/",
            ),
        ),
    ]
