# Generated by Django 4.2.9 on 2024-10-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_usercomplaint"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="duration",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
